---
- name: Computer configuration
  hosts: win

  pre_tasks:
    - name: Include playbook user configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ role }}.yml"
      tags: ["always"]

  roles:
    - common

  handlers:
    - name: Configure Firewall rules (RDS).
      ansible.windows.win_shell: >
        "{{ 'Enable-NetFirewallRule' if remote_desktop_enabled else 'Disable-NetFirewallRule' }}
        -DisplayGroup 'Remotedesktop'"


  tasks:


