---
- hosts: win

  pre_tasks:

    - set_fact:
        device_config: "{{ ansible_hostname.split('-') }}"

    - set_fact:
        device_company: "{{  device_config.0 }}"
        device_role: "{{  device_config.1 }}"
        device_type: "{{  device_config.2 }}"
        employee_name: "{{  device_config.3 }}"
        employee_surname: "{{  device_config.4 }}"

    - debug:
        msg:
          - "{{ device_role }}"
          - "{{ employee_surname}}"

  roles:
    - common

  tasks:

    - include_role:
        name: "{{ device_role }}"

