---
- name: Computer configuration
  hosts: win

  roles:
    - common

  handlers:
    - name: Configure Firewall rules (RDS).
      ansible.windows.win_shell: >
        "{{ 'Enable-NetFirewallRule' if remote_desktop_enabled else 'Disable-NetFirewallRule' }}
        -DisplayGroup 'Remotedesktop'"


  tasks:
    - name: Include role.
      include_role:
        name: {{ COMPUTERNAME }}


