---
- hosts: deploy

  # The hostname will determine the device role and username
  # sample hostname gdc-accounting-dt-name-surname
  # hostname will be split and be put to variables needed for the playbook
  pre_tasks:

    - set_fact:
        device_config: "{{ ansible_hostname.split('-') }}"

    - set_fact:
        device_company: "{{  device_config.0 }}"
        device_role: "{{  device_config.1 }}"
        device_type: "{{  device_config.2 }}"
        employee_name: "{{  device_config.3 }}"
        employee_surname: "{{  device_config.4 }}"

    - name: Warn logged in users
      community.windows.win_msg:
        display_seconds: 300
        msg: "Starting automated provisioning of this PC for {{ employee_name }} user as {{ device_role }} role. Email will be sent after provisioning. Thank you."

  roles:
    - common

  tasks:

    - include_role:
        name: "{{ device_role }}"
      when: device_role != 'common'

  post_tasks:

    - name: remove privileges
      ansible.builtin.import_tasks:
        file: roles/common/tasks/post_task.yml
      tags: ["post_task"]

    - name: Warn logged in users
      community.windows.win_msg:
        display_seconds: 300
        msg: "Configuration succesfull!"
