- name: Ensure user administrator is present
  ansible.windows.win_user:
    name: Administrator
    password: '{{ admin_password }}'
    state: present
    account_disabled: false
    groups:
      - Administrators
