---
- name: adding driver package
  ansible.windows.win_powershell:
    script: |
      pnputil /add-driver "C:\installer\KX_Universal_Printer_Driver\Kx83_UPD_8.3.0815_RC5_en\64bit\OEMSETUP.INF" /install

- name: add printer port
  ansible.windows.win_powershell:
    script: |
      if (-not(Get-PrinterPort | Select-String "{{ PrinterPortName }}")) {
        Add-PrinterPort -Name "{{ PrinterPortName }}" -PrinterHostAddress "{{ PrinterIP }}"
      }

- name: add printer driver
  ansible.windows.win_powershell:
    script: |
      if (-not(Get-Printer | Select-String "{{ PrintDriverName }}")) {
        Add-PrinterDriver -Name "{{ PrintDriverName }}"
      }

- name: add printer
  ansible.windows.win_powershell:
    script: |
      if (-not(Get-Printer | Select-String "{{ PrinterName }}")) {
        Add-Printer -Name "{{ PrinterName }}" -DriverName "{{ PrintDriverName }}" -PortName "{{ PrinterPortName }}"
      }

- name: black and white printing
  win_shell: Set-PrintConfiguration -PrinterName "{{ PrinterName }}" -Color 0 # B&W

- name: single-sided printing
  win_shell: Set-PrintConfiguration -PrinterName "{{ PrinterName }}" -DuplexingMode 'OneSided'

- name: default letter papersize
  win_shell: Set-PrintConfiguration -PrinterName "{{ PrinterName }}" -PaperSize 'Letter'


################################################################


- name: install Install prt-gdc-imagerunner01-purchasing-11x7
  ansible.windows.win_powershell:
    script: |
      pnputil /add-driver "C:\installer\ImageRunner-ADV4525\x64\etc\CNP60MA64.INF" /install

- name: add printer port
  ansible.windows.win_powershell:
    script: |
      Add-PrinterPort -Name "{{ IRPrinterPortName }}" -PrinterHostAddress "{{ IRPrinterIP }}"


- name: add printer driver
  ansible.windows.win_powershell:
    script: |
      if (-not(Get-Printer | Select-String "{{ IRPrintDriverName }}")) {
        Add-PrinterDriver -Name "{{ IRPrintDriverName }}"
      }

- name: add printer
  ansible.windows.win_powershell:
    script: |
      Add-Printer -Name "{{ IRPrinterName }}" -DriverName "{{ IRPrintDriverName }}" -PortName "{{ IRPrinterPortName }}"


- name: black and white printing
  win_shell: Set-PrintConfiguration -PrinterName "{{ IRPrinterName }}" -Color 0 # B&W

- name: single-sided printing
  win_shell: Set-PrintConfiguration -PrinterName "{{ IRPrinterName }}" -DuplexingMode 'OneSided'
  ignore_errors: true

- name: default letter papersize
  win_shell: Set-PrintConfiguration -PrinterName "{{ IRPrinterName }}" -PaperSize 'Letter'
  ignore_errors: true

